apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-bluegreen-active
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: active.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-bluegreen-active
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-bluegreen-preview
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: preview.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-bluegreen-preview
                port:
                  number: 80
