apiVersion: v1
kind: Service
metadata:
  name: nginx-bluegreen-active
  namespace: demo
spec:
  selector:
    app: nginx-bluegreen
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-bluegreen-preview
  namespace: demo
spec:
  selector:
    app: nginx-bluegreen
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
